### ISSUE TITLE
Added +/- button to the following: - [merged]

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/dungeonworld#151]
In GitLab by @Puddinglord on Mar 8, 2021, 19:43

_Merges master -> master-21-integration_

- Experience
- Coins
- Health

Let me know if this is acceptable. I wanted to add some QoL buttons to the character sheet when I play. I thought others could use them as well. I've got a list of changes I plan on making and so there should be a few more merge requests coming. I wanted to do them incrementally though so there could be a discussion about each category of updates.

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Mar 29, 2021, 08:47

@Puddinglord I haven't tested this locally yet, but this looks good to me in principal. I'll do some testing this week and see if I can get it merged. :thumbsup:

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Apr 3, 2021, 18:52

changed target branch from `master` to `beta-21-integration`

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Apr 3, 2021, 18:52

approved this merge request

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Apr 3, 2021, 18:54

changed target branch from `beta-21-integration` to `master-21-integration`

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Apr 3, 2021, 18:54

approved this merge request

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Apr 3, 2021, 18:54

mentioned in commit 2bfe0acad4a123a73d1338edf1827087e0b14a92

**Comment by Puddinglord** [comment]
Thank you!
